spring:
  application:
    name: server-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.214.129:8848
server:
  port: 8070
management:
  endpoints:
    web:
      exposure:
        include: "*"