spring:
  application:
    name: server-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.214.129:8848
server:
  port: 8060
management:
  endpoints:
    web:
      exposure:
        include: "*"